# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-06 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0028_auto_20210614_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_job_id', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('ManualResubmit', 'ManualResubmit')], db_index=True, max_length=32)),
                ('resubmission_reason', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
